services:
  odoo:
    container_name: odoo-17
    image: odoo
    env_file: .env
    ports:
      - "8069:8069"
    volumes:
      - data:/var/lib/odoo
      - ./config:/odoo.conf
      - ./custom-addons:/mnt/extra-addons
volumes:
  data:
